# Generated by Django 4.2 on 2023-04-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('davlat', models.CharField(max_length=50)),
                ('logo', models.FileField(upload_to='')),
                ('president', models.CharField(max_length=50)),
                ('murabbiy', models.CharField(max_length=50)),
                ('yil', models.DateField()),
                ('eng_katta_t', models.FloatField()),
                ('eng_katta_sotuv', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Hozirgimavsum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavsum', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('pozitsiya', models.CharField(max_length=50)),
                ('millat', models.CharField(max_length=50)),
                ('tr_narx', models.FloatField()),
                ('tug_yil', models.DateField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.club')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narx', models.FloatField()),
                ('tax_narx', models.FloatField()),
                ('mavsum', models.CharField(max_length=50)),
                ('eski', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sotilgan', to='asosiy.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.player')),
                ('yangi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.club')),
            ],
        ),
    ]
